export const USER_INFO_API = "https://6dyqv.mocklab.io/getusers"
export const  ADD_USER_API = "https://6dyqv.mocklab.io/addusers"
export const  APPEND_USER_INFO_API = "https://6dyqv.mocklab.io/appenduserinfo"
export const  UPDATE_USER_INFO_API = "https://6dyqv.mocklab.io/updateuser"
export const  DELETE_USER_API = "https://6dyqv.mocklab.io/deleteuser"
